name: lecture-datascience
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2020.11
  - pip
  - pip:
    - jupyter-book>=0.11.0,<0.12.0
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - sphinx-exercise
    - joblib
    - interpolation
    - sphinx-tojupyter
    - fiona 
    - geopandas 
    - pyLDAvis >= 3.3.0
    - gensim 
    - folium 
    - descartes 
    - pyarrow
    - xgboost
    - graphviz
    - scikit-learn >= 0.24.0
    - bokeh
    - sphinxcontrib-bibtex
    - quantecon-book-theme>=0.2.5,<0.3.0
    - nltk
    - seaborn
    - patsy
    - quandl
    - statsmodels
    - quantecon
    - openpyxl
    - pandas_datareader
    - plotly
    - lxml
  - conda:
    - python-graphviz