name: Format Markdown Files

on:
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    #   - name: Setup Julia
    #     uses: julia-actions/setup-julia@v1
    #     with:
    #       version: 1.9

    #   - name: Install JuliaFormatter.jl
    #     run: julia -e 'import Pkg; Pkg.add("JuliaFormatter")'

      - name: Get Changed Files
        id: changed_files
        uses: actions/changed-files@v1

      - name: Format Markdown Files
        run: |
          for file in ${{ steps.changed_files.outputs.files }}; do
            if [[ "$file" == *.md ]]; then
              julia format_myst.jl "$file"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Apply formatting to Markdown files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
