name: Format Markdown Files

on:
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.6

      - name: Install JuliaFormatter.jl
        run: julia -e 'import Pkg; Pkg.add("JuliaFormatter")'

      - name: Format Markdown Files
        run: |
          modified_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.md$')
          for file in $modified_files; do
            julia format_myst.jl "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
